name = "livestore-workshop-2025"
main = "./src/index.ts"
compatibility_date = "2024-05-12"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "SyncBackend"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackend"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-db"
database_id = "120869b0-bb6f-4d3a-94d5-0761782fc11c"

# Enable logs for observability (Optional, you can remove this section)
[observability.logs]
enabled = true

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
