name = "websocket-server"
main = "./src/index.ts"
compatibility_date = "2024-05-12"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-test"
database_id = "${LIVESTORE_CF_SYNC_DATABASE_ID}"

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
