name = "livestore-workshop-2025"
main = "./src/index.ts"
compatibility_date = "2024-05-12"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "SyncBackend"

[[migrations]]
tag = "v1"
new_classes = ["SyncBackend"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-db"
database_id = "4546e240-ec34-4a40-a31f-958a72dac230"

# Enable logs for observability (Optional, you can remove this section)
[observability.logs]
enabled = true

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
