name = "websocket-server"
main = "./src/index.ts"
compatibility_date = "2024-05-12"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-test"
database_id = "fd58992d-e1fd-45a2-9e41-2f1bbe80f7ea"

# Enable logs for observability (Optional, you can remove this section)
[observability.logs]
enabled = true

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
